version: "3.4"
services:
  pg:
    image: "postgis/postgis:14-3.3"
    ports:
    - 8433:5432
    environment: 
    - POSTGRES_PASSWORD=${SUPERUSERPASS}
    volumes:
    - ./create_postgres_stack.sql:/docker-entrypoint-initdb.d/create_postgres_stack.sql
    - pgdata:/var/lib/postgresql/data
    restart: always
  # pg_tileserv:
  #   image: "pramsey/pg_tileserv:latest"
  #   ports:
  #   - 8801:7800
  #   environment:
  #   - DATABASE_URL=${DATABASE_URL_GEO7630}
  #   volumes:
  #   - ./pg_tileserv.toml:/etc/pg_tileserv.toml
  #   depends_on:
  #   - "pg"
  #   restart: always
  # pg_featureserv:
  #   image: "pramsey/pg_featureserv:latest"
  #   ports:
  #   - 9000:9000
  #   environment:
  #   # CHANGE connection string from .env file
  #   - DATABASE_URL=${DATABASE_URL_GEO7630}
  #   depends_on:
  #   - "pg"
  #   restart: always
  geoserver:
      image: geosolutionsit/geoserver
      ports:
      - 8080:8080
      environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS="PGRaster"
      volumes:
      - ./web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
      - ./Laboratoires/Lab7/geoserverData:/var/geoserver/datadir
      restart: always
  server-web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./:/usr/share/nginx/html
volumes:
  pgdata:
    name: installation_pgdata